server.port=8080

spring.datasource.url=jdbc:postgresql://localhost:5432/SchoolManagmentSystem
spring.datasource.username=postgres
spring.datasource.password=\#Ademokkaaa0327

spring.datasource.driver-class-name=org.postgresql.Driver

